#!/bin/bash

# csv2ics
# M. Brent Harp
# 2011
#
# Converts an CSV file containing event information to an 
# ICS file.  The events are all assumed to be all day events.
#

echo BEGIN:VCALENDAR
echo PRODID:`basename $0`
echo VERSION:2.0
echo METHOD:PUBLISH
while IFS='	' read date summary desc
do
	echo BEGIN:VEVENT
	echo UID:`uuidgen`
	echo SUMMARY:${summary}
	echo DESCRIPTION:${desc}
	echo X-ALT-DESC\;FMTPTYPE=text/html:\<html\>\<body\>${desc}\</body\>\</html\>
	echo DTSTART\;VALUE=DATE:`date -d "${date}" +%Y%m%d`
	echo DTEND\;VALUE=DATE:`date -d "${date} + 1 day" +%Y%m%d`
	echo STATUS:CONFIRMED
	echo CLASS:PUBLIC
	echo X-MICROSOFT-CDO-ALLDAYEVENT:TRUE
	echo X-MICROSOFT-CDO-INTENDEDSTATUS:FREE
	echo TRANSP:TRANSPARENT
	echo X-MICROSOFT-DISALLOW-COUNTER:TRUE
	echo BEGIN:VALARM
	echo ACTION:DISPLAY
	echo TRIGGER\;RELATED=START:-PT2880M
	echo DESCRIPTION:Reminder
	echo END:VALARM
	echo END:VEVENT
done
echo END:VCALENDAR
